import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    IS_MAINTENANCE: z.enum(["true", "false"]).default("false"),
    // ShiftBrief AI (optional). When all three are present, the combined brief
    // is generated by AI; otherwise the offline keyword parser is used.
    AI_BASE_URL: z.string().url().optional(),
    AI_API_KEY: z.string().min(1).optional(),
    AI_MODEL: z.string().min(1).default("llama-3.3-70b-versatile"),
    // Optional. Only some providers/models accept it (e.g. Gemini needs "none"
    // to disable thinking; Groq's models reject it). Omit unless required.
    AI_REASONING_EFFORT: z.string().min(1).optional(),
    // Supabase (optional). When both are present, storage switches from
    // in-memory to durable Supabase REST storage.
    SUPABASE_URL: z.string().url().optional(),
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_SITE_URL: z.url(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    IS_MAINTENANCE: process.env.IS_MAINTENANCE,
    AI_BASE_URL: process.env.AI_BASE_URL,
    AI_API_KEY: process.env.AI_API_KEY,
    AI_MODEL: process.env.AI_MODEL,
    AI_REASONING_EFFORT: process.env.AI_REASONING_EFFORT,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  },
  emptyStringAsUndefined: true,
});
